<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <Platforms>x64;ARM64</Platforms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PlatformTarget>$(Platform)</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="3.6.3" />
    <PackageReference Include="System.IO.Abstractions" Version="21.0.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Community.PowerToys.Run.Plugin.StackOverflow\Community.PowerToys.Run.Plugin.StackOverflow.csproj" />
  </ItemGroup>

</Project>
